#define LEVEL_SENSOR_LOW_PIN 0
#define LEVEL_SENSOR_LEVEL_1_PIN 0
#define LEVEL_SENSOR_LEVEL_2_PIN 0
#define LEVEL_SENSOR_LEVEL_3_PIN 0

#define DUTY_SELECT_PUMP_1_PIN 0
#define DUTY_SELECT_PUMP_2_PIN 0
#define DUTY_SELECT_PUMP_3_PIN 0
#define DUTY_SELECT_PUMP_4_PIN 0
#define DUTY_SELECT_PUMP_5_PIN 0
#define DUTY_SELECT_PUMP_6_PIN 0

#define ASSIST_SELECT_GROUP_1_PUMP_1_PIN 0
#define ASSIST_SELECT_GROUP_1_PUMP_2_PIN 0
#define ASSIST_SELECT_GROUP_1_PUMP_3_PIN 0
#define ASSIST_SELECT_GROUP_1_PUMP_4_PIN 0
#define ASSIST_SELECT_GROUP_1_PUMP_5_PIN 0
#define ASSIST_SELECT_GROUP_1_PUMP_6_PIN 0

#define ASSIST_SELECT_GROUP_2_PUMP_1_PIN 0
#define ASSIST_SELECT_GROUP_2_PUMP_2_PIN 0
#define ASSIST_SELECT_GROUP_2_PUMP_3_PIN 0
#define ASSIST_SELECT_GROUP_2_PUMP_4_PIN 0
#define ASSIST_SELECT_GROUP_2_PUMP_5_PIN 0
#define ASSIST_SELECT_GROUP_2_PUMP_6_PIN 0

#define OUTPUT_PUMP_1_ENABLE_PIN 0
#define INPUT_PUMP_1_RUNNING_PIN 0
#define OUTPUT_PUMP_2_ENABLE_PIN 0
#define INPUT_PUMP_2_RUNNING_PIN 0
#define OUTPUT_PUMP_3_ENABLE_PIN 0
#define INPUT_PUMP_3_RUNNING_PIN 0
#define OUTPUT_PUMP_4_ENABLE_PIN 0
#define INPUT_PUMP_4_RUNNING_PIN 0
#define OUTPUT_PUMP_5_ENABLE_PIN 0
#define INPUT_PUMP_5_RUNNING_PIN 0
#define OUTPUT_PUMP_6_ENABLE_PIN 0
#define INPUT_PUMP_6_RUNNING_PIN 0


void initialise_pins() {

    pinMode(LEVEL_SENSOR_LOW_PIN, INPUT_PULLUP);
    pinMode(LEVEL_SENSOR_LEVEL_1_PIN, INPUT_PULLUP);
    pinMode(LEVEL_SENSOR_LEVEL_2_PIN, INPUT_PULLUP);
    pinMode(LEVEL_SENSOR_LEVEL_3_PIN, INPUT_PULLUP);

    pinMode(DUTY_SELECT_PUMP_1_PIN, INPUT_PULLUP);
    pinMode(DUTY_SELECT_PUMP_2_PIN, INPUT_PULLUP);
    pinMode(DUTY_SELECT_PUMP_3_PIN, INPUT_PULLUP);
    pinMode(DUTY_SELECT_PUMP_4_PIN, INPUT_PULLUP);
    pinMode(DUTY_SELECT_PUMP_5_PIN, INPUT_PULLUP);
    pinMode(DUTY_SELECT_PUMP_6_PIN, INPUT_PULLUP);
    
    pinMode(ASSIST_SELECT_GROUP_1_PUMP_1_PIN, INPUT_PULLUP);
    pinMode(ASSIST_SELECT_GROUP_1_PUMP_2_PIN, INPUT_PULLUP);
    pinMode(ASSIST_SELECT_GROUP_1_PUMP_3_PIN, INPUT_PULLUP);
    pinMode(ASSIST_SELECT_GROUP_1_PUMP_4_PIN, INPUT_PULLUP);
    pinMode(ASSIST_SELECT_GROUP_1_PUMP_5_PIN, INPUT_PULLUP);
    pinMode(ASSIST_SELECT_GROUP_1_PUMP_6_PIN, INPUT_PULLUP);
    
    pinMode(ASSIST_SELECT_GROUP_2_PUMP_1_PIN, INPUT_PULLUP);
    pinMode(ASSIST_SELECT_GROUP_2_PUMP_2_PIN, INPUT_PULLUP);
    pinMode(ASSIST_SELECT_GROUP_2_PUMP_3_PIN, INPUT_PULLUP);
    pinMode(ASSIST_SELECT_GROUP_2_PUMP_4_PIN, INPUT_PULLUP);
    pinMode(ASSIST_SELECT_GROUP_2_PUMP_5_PIN, INPUT_PULLUP);
    pinMode(ASSIST_SELECT_GROUP_2_PUMP_6_PIN, INPUT_PULLUP);

    pinMode(OUTPUT_PUMP_1_ENABLE_PIN, OUTPUT);
    pinMode(INPUT_PUMP_1_RUNNING_PIN, INPUT_PULLUP);

    pinMode(OUTPUT_PUMP_2_ENABLE_PIN, OUTPUT);
    pinMode(INPUT_PUMP_2_RUNNING_PIN, INPUT_PULLUP);

    pinMode(OUTPUT_PUMP_3_ENABLE_PIN, OUTPUT);
    pinMode(INPUT_PUMP_3_RUNNING_PIN, INPUT_PULLUP);

    pinMode(OUTPUT_PUMP_4_ENABLE_PIN, OUTPUT);
    pinMode(INPUT_PUMP_4_RUNNING_PIN, INPUT_PULLUP);

    pinMode(OUTPUT_PUMP_5_ENABLE_PIN, OUTPUT);
    pinMode(INPUT_PUMP_5_RUNNING_PIN, INPUT_PULLUP);

    pinMode(OUTPUT_PUMP_6_ENABLE_PIN, OUTPUT);
    pinMode(INPUT_PUMP_6_RUNNING_PIN, INPUT_PULLUP);
}